(()=>{
'use strict';
const $=s=>document.querySelector(s),canvas=$('#view'),statusEl=$('#status'),loadingEl=$('#loading');
if(!window.THREE){loadingEl.innerHTML='<div><h2>Could not load 3D engine</h2><p>Open in Safari and check the internet connection.</p></div>';return}
const MOBILE=/iPad|iPhone|Android/i.test(navigator.userAgent),CHUNK=180,OVERLAP=12,MAX_CACHE_AGE=7*86400000;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc3d4);scene.fog=new THREE.Fog(0x9fc3d4,430,1180);
const camera=new THREE.PerspectiveCamera(56,innerWidth/innerHeight,.1,2500);const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,MOBILE?1.45:1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;
const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.maxPolarAngle=Math.PI*.475;controls.minDistance=28;controls.maxDistance=900;controls.screenSpacePanning=false;
scene.add(new THREE.HemisphereLight(0xecfaff,0x4d5d45,1.72));const sun=new THREE.DirectionalLight(0xffefd0,1.55);sun.position.set(-260,360,180);sun.castShadow=true;sun.shadow.mapSize.set(MOBILE?1024:2048,MOBILE?1024:2048);sun.shadow.camera.left=-420;sun.shadow.camera.right=420;sun.shadow.camera.top=420;sun.shadow.camera.bottom=-420;sun.shadow.bias=-.0008;scene.add(sun);
const world=new THREE.Group();scene.add(world);
const shared={
 groundA:new THREE.MeshStandardMaterial({color:0x879b78,roughness:1}),groundB:new THREE.MeshStandardMaterial({color:0x849776,roughness:1}),
 chunkLine:new THREE.LineBasicMaterial({color:0xc5dfbd,transparent:true,opacity:.16}),edge:new THREE.LineBasicMaterial({color:0x253139,transparent:true,opacity:.32}),
 sidewalk:new THREE.MeshStandardMaterial({color:0xa8a293,roughness:1}),marking:new THREE.MeshBasicMaterial({color:0xe7dfbf}),rail:new THREE.MeshStandardMaterial({color:0x43484b,roughness:1}),
 water:new THREE.MeshStandardMaterial({color:0x69a9c3,roughness:.28,metalness:.04,transparent:true,opacity:.9,side:THREE.DoubleSide}),
 trunk:new THREE.MeshStandardMaterial({color:0x6f543b,roughness:1}),leaf:new THREE.MeshStandardMaterial({color:0x4e7952,roughness:1,flatShading:true}),
 lamp:new THREE.MeshStandardMaterial({color:0x4b5357,roughness:.8,metalness:.15}),lampGlow:new THREE.MeshBasicMaterial({color:0xffe6a5}),
 car:[0xb74f47,0x3f6e94,0xd2c7a6,0x353a3d,0x8b5a78,0xc28a3c].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.6,metalness:.12})),
 road:{},area:{},building:{},roof:{}
};
const windowTexture=(()=>{const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.fillStyle='#27353b';x.fillRect(0,0,64,64);for(let r=4;r<64;r+=16)for(let q=4;q<64;q+=16){x.fillStyle=((r+q)%32)?'#a7c2c5':'#d8c884';x.globalAlpha=.62;x.fillRect(q,r,8,8)}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.LinearFilter;return t})();
const windowMat=new THREE.MeshBasicMaterial({map:windowTexture,transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false});
let origin={lat:45.5231,lon:-122.6765},chunks=new Map(),queue=[],active=0,generation=0,lastStream=0,panMode=true,totalFeatures=0,lastCenterKey='',toastTimer=null,dbPromise=null;
const buildingPalette=[0xd8c59f,0xc9ad83,0xbcc0b8,0xc58e77,0xddd3bd,0xa5aca4,0xc7bba7];
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2600)}
function hash(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let s=hash(seed)||1;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function geoToWorld(lat,lon){return{x:(lon-origin.lon)*111320*Math.cos(origin.lat*Math.PI/180),z:(lat-origin.lat)*110540}}
function worldToGeo(x,z){return{lat:origin.lat+z/110540,lon:origin.lon+x/(111320*Math.cos(origin.lat*Math.PI/180))}}
function snap(v){const n=+$('#voxel').value||0;return n?Math.round(v/n)*n:v}
function parseMeters(v){if(v==null)return NaN;const s=String(v).trim(),n=parseFloat(s);if(!Number.isFinite(n))return NaN;return /ft|feet|foot|'/i.test(s)?n*.3048:n}
function material(store,color,extra={}){const k=String(color)+JSON.stringify(extra);return store[k]||(store[k]=new THREE.MeshStandardMaterial({color,roughness:.9,...extra}))}
function roadMat(c){return material(shared.road,c,{polygonOffset:true,polygonOffsetFactor:-2})}function areaMat(c){return material(shared.area,c,{side:THREE.DoubleSide})}function buildingMat(c){return material(shared.building,c,{flatShading:true})}function roofMat(c){return material(shared.roof,c,{flatShading:true})}
function disposeGroup(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose()});world.remove(g)}
function clearWorld(){generation++;queue=[];active=0;for(const c of chunks.values())disposeGroup(c.group);chunks.clear();totalFeatures=0;updateStats()}
function chunkKey(cx,cz){return cx+','+cz}
function chunkBounds(c){const h=CHUNK/2;return{minX:c.cx*CHUNK-h,maxX:c.cx*CHUNK+h,minZ:c.cz*CHUNK-h,maxZ:c.cz*CHUNK+h}}
function inBounds(x,z,b,pad=0){return x>=b.minX-pad&&x<=b.maxX+pad&&z>=b.minZ-pad&&z<=b.maxZ+pad}
function cleanPoints(geometry,closed=false){if(!geometry)return[];const pts=[];for(const p of geometry){if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))continue;const w=geoToWorld(p.lat,p.lon),q={x:snap(w.x),z:snap(w.z)};const a=pts[pts.length-1];if(!a||Math.hypot(q.x-a.x,q.z-a.z)>.18)pts.push(q)}if(closed&&pts.length>2){const a=pts[0],b=pts[pts.length-1];if(Math.hypot(a.x-b.x,a.z-b.z)>.18)pts.push({...a})}return pts}
function centroid(pts){let x=0,z=0,n=0;for(const p of pts){x+=p.x;z+=p.z;n++}return n?{x:x/n,z:z/n}:{x:0,z:0}}
function polygonArea(pts){let a=0;for(let i=0,j=pts.length-1;i<pts.length;j=i++)a+=(pts[j].x*pts[i].z-pts[i].x*pts[j].z);return Math.abs(a*.5)}
function pointInPoly(x,z,p){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a.z>z)!=(b.z>z))&&(x<(b.x-a.x)*(z-a.z)/(b.z-a.z+1e-9)+a.x))inside=!inside}return inside}
function makeShape(pts){if(pts.length<3)return null;const p=pts.slice(),f=p[0],l=p[p.length-1];if(Math.hypot(f.x-l.x,f.z-l.z)<.2)p.pop();if(p.length<3)return null;const s=new THREE.Shape();s.moveTo(p[0].x,-p[0].z);for(let i=1;i<p.length;i++)s.lineTo(p[i].x,-p[i].z);s.closePath();return s}
function addChunkBase(c){const group=c.group,b=chunkBounds(c),mat=((c.cx+c.cz)&1)?shared.groundA:shared.groundB;const ground=new THREE.Mesh(new THREE.BoxGeometry(CHUNK-.35,1,CHUNK-.35),mat);ground.position.set(c.cx*CHUNK,-.56,c.cz*CHUNK);ground.receiveShadow=true;group.add(ground);const e=new THREE.EdgesGeometry(new THREE.BoxGeometry(CHUNK,.02,CHUNK));const line=new THREE.LineSegments(e,shared.chunkLine);line.position.set(c.cx*CHUNK,.015,c.cz*CHUNK);group.add(line);const pin=new THREE.Mesh(new THREE.CylinderGeometry(1.7,1.7,.15,12),new THREE.MeshBasicMaterial({color:0xbafd67,transparent:true,opacity:.55}));pin.position.set(c.cx*CHUNK,.1,c.cz*CHUNK);group.add(pin);c.pin=pin}
function geometries(el){if(el.type==='way'&&el.geometry)return[{geometry:el.geometry,id:el.id,tags:el.tags||{}}];if(el.type==='relation'&&el.members)return el.members.filter(m=>m.type==='way'&&m.geometry&&(!m.role||m.role==='outer')).map((m,i)=>({geometry:m.geometry,id:el.id+'-'+i,tags:el.tags||{}}));return[]}
function areaStyle(t){if(t.natural==='water'||['reservoir','basin'].includes(t.landuse))return{c:0x69a9c3,y:.025,water:true,trees:0};if(t.natural==='wood'||t.landuse==='forest')return{c:0x547c58,y:.018,trees:1};if(['park','garden'].includes(t.leisure))return{c:0x6d9870,y:.019,trees:.45};if(t.leisure==='pitch')return{c:0x72906b,y:.02,trees:0};if(['grass','meadow','recreation_ground','village_green','cemetery'].includes(t.landuse))return{c:0x76956d,y:.017,trees:.18};if(['commercial','retail'].includes(t.landuse))return{c:0x9b8f82,y:.014,trees:0};if(t.landuse==='industrial')return{c:0x8c8a82,y:.014,trees:0};return{c:0x829775,y:.012,trees:0}}
function roadStyle(t){const h=t.highway||'';if(['motorway','trunk'].includes(h))return{w:12,c:0x48535a,walk:0,mark:1,cars:1};if(['primary','secondary'].includes(h))return{w:9,c:0x525e64,walk:1,mark:1,cars:1};if(h==='tertiary')return{w:7.5,c:0x576268,walk:1,mark:1,cars:1};if(['residential','unclassified'].includes(h))return{w:6.2,c:0x5d676c,walk:1,mark:0,cars:.55};if(['service','living_street'].includes(h))return{w:4.5,c:0x666e72,walk:.5,mark:0,cars:.15};if(['pedestrian','footway','path','cycleway','steps'].includes(h))return{w:2.1,c:0x9d927b,walk:0,mark:0,cars:0};return{w:4,c:0x626a6e,walk:0,mark:0,cars:0}}
function addArea(group,pts,style){const s=makeShape(pts);if(!s)return false;try{const geo=new THREE.ShapeGeometry(s);geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,style.water?shared.water:areaMat(style.c));mesh.position.y=style.y;mesh.receiveShadow=true;group.add(mesh);return true}catch(e){return false}}
function buildingHeight(t,id){let h=parseMeters(t.height);if(Number.isFinite(h))return Math.max(3,Math.min(180,h));const lv=parseFloat(t['building:levels']);if(Number.isFinite(lv))return Math.max(3,Math.min(180,lv*3.15));if(['garage','garages','shed','roof','carport'].includes(t.building))return 3.2;const r=hash(id)%1000/1000;return 5.5+Math.pow(r,1.55)*27}
function minHeight(t){let h=parseMeters(t.min_height);if(Number.isFinite(h))return Math.max(0,h);const l=parseFloat(t['building:min_level']);return Number.isFinite(l)?l*3.15:0}
function buildingColor(t,id){const m=(t['building:material']||'').toLowerCase(),c=t['building:colour']||t['building:color'];if(c&&/^#?[0-9a-f]{6}$/i.test(c))return parseInt(c.replace('#',''),16);if(m.includes('brick'))return 0xb97961;if(m.includes('glass'))return 0x91adb4;if(m.includes('concrete'))return 0xb8b6ae;if(m.includes('wood'))return 0xb18c66;return buildingPalette[hash(id)%buildingPalette.length]}
function roofColor(t,id){const c=t['roof:colour']||t['roof:color'];if(c&&/^#?[0-9a-f]{6}$/i.test(c))return parseInt(c.replace('#',''),16);const m=(t['roof:material']||'').toLowerCase();if(m.includes('tile'))return 0x8e5845;if(m.includes('metal'))return 0x6e7778;if(m.includes('slate'))return 0x4e565d;return[0x77786f,0x806b5b,0x666e70,0x8b7562][hash(id+'r')%4]}
function addGableRoof(group,pts,y,color,shapeTag){let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z)}const w=maxX-minX,d=maxZ-minZ;if(w<3||d<3)return;const cx=(minX+maxX)/2,cz=(minZ+maxZ)/2,rh=Math.min(5,Math.max(1.5,Math.min(w,d)*.28));if(['pyramidal','hipped','dome','onion'].includes(shapeTag)){const geo=shapeTag==='dome'?new THREE.SphereGeometry(1,10,5,0,Math.PI*2,0,Math.PI/2):new THREE.ConeGeometry(1,1,4);const m=new THREE.Mesh(geo,roofMat(color));m.position.set(cx,y+(shapeTag==='dome'?0:rh/2),cz);m.scale.set(w*.55,shapeTag==='dome'?rh:rh,d*.55);m.rotation.y=Math.PI/4;group.add(m);return}const alongX=w>=d;const L=alongX?w:d,S=alongX?d:w;const p=[[-L/2,0,-S/2],[L/2,0,-S/2],[-L/2,0,S/2],[L/2,0,S/2],[-L/2,rh,0],[L/2,rh,0]],idx=[0,1,5,0,5,4,2,4,5,2,5,3,0,4,2,1,3,5,0,2,3,0,3,1];const pos=[];for(const i of idx)pos.push(...p[i]);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.computeVertexNormals();const m=new THREE.Mesh(geo,roofMat(color));m.position.set(cx,y,cz);if(!alongX)m.rotation.y=Math.PI/2;group.add(m)}
function addWindows(group,pts,base,h){if(+$('#detail').value<2||h<8)return;for(let i=0;i<Math.min(pts.length-1,8);i++){const a=pts[i],b=pts[i+1],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);if(len<7)continue;const ph=Math.min(h*.7,24),geo=new THREE.PlaneGeometry(len*.86,ph),m=new THREE.Mesh(geo,windowMat);m.position.set((a.x+b.x)/2+(-dz/len)*.06,base+h*.5,(a.z+b.z)/2+(dx/len)*.06);m.rotation.y=Math.atan2(-dz,dx);group.add(m)}}
function addBuilding(group,pts,t,id){const s=makeShape(pts);if(!s)return false;const h=buildingHeight(t,id),base=minHeight(t),color=buildingColor(t,id);try{const geo=new THREE.ExtrudeGeometry(s,{depth:h,bevelEnabled:false,steps:1,curveSegments:1});geo.rotateX(-Math.PI/2);geo.translate(0,base,0);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,buildingMat(color));mesh.castShadow=+$('#detail').value>0;mesh.receiveShadow=true;group.add(mesh);if(+$('#detail').value>0){const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo,30),shared.edge);group.add(edges)}const rshape=(t['roof:shape']||'flat').toLowerCase(),rc=roofColor(t,id);if(rshape==='flat'||rshape==='skillion'){const rg=new THREE.ShapeGeometry(s);rg.rotateX(-Math.PI/2);const rm=new THREE.Mesh(rg,roofMat(rc));rm.position.y=base+h+.025;group.add(rm)}else addGableRoof(group,pts,base+h,rc,rshape);if(+$('#detail').value>0&&polygonArea(pts)>180&&h>12){const c=centroid(pts),r=rng(id+'unit'),u=2.2+r()*2.8;const box=new THREE.Mesh(new THREE.BoxGeometry(u*1.5,1.2+r()*1.8,u),roofMat(0x686f6d));box.position.set(c.x,base+h+box.geometry.parameters.height/2,c.z);group.add(box)}addWindows(group,pts,base,h);return true}catch(e){return false}}
function addSegmentBox(group,a,b,width,mat,y=.07,height=.11){const dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);if(len<.25)return null;const m=new THREE.Mesh(new THREE.BoxGeometry(len,height,width),mat);m.position.set((a.x+b.x)/2,y,(a.z+b.z)/2);m.rotation.y=-Math.atan2(dz,dx);m.receiveShadow=true;group.add(m);return{mesh:m,len,dx:dx/len,dz:dz/len,a,b}}
function renderRoad(group,pts,t,bounds,carList){const st=roadStyle(t),layer=parseFloat(t.layer)||0,y=t.bridge?1.1+layer*.55:.07+layer*.12;let rendered=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],mx=(a.x+b.x)/2,mz=(a.z+b.z)/2;if(!inBounds(mx,mz,bounds,2))continue;if(st.walk)addSegmentBox(group,a,b,st.w+3.2*st.walk,shared.sidewalk,y-.035,.09);const seg=addSegmentBox(group,a,b,st.w,roadMat(st.c),y,.12);if(!seg)continue;rendered++;if(st.mark&&+$('#detail').value>0){const dash=5,gap=5,n=Math.floor(seg.len/(dash+gap));for(let d=0;d<n;d++){const start=(d+.5)*(dash+gap)-seg.len/2,mid={x:mx+seg.dx*start,z:mz+seg.dz*start},p1={x:mid.x-seg.dx*dash/2,z:mid.z-seg.dz*dash/2},p2={x:mid.x+seg.dx*dash/2,z:mid.z+seg.dz*dash/2};addSegmentBox(group,p1,p2,.18,shared.marking,y+.07,.035)}}if(st.cars&&+$('#detail').value>0&&seg.len>18){const r=rng((t.name||'road')+i+Math.round(mx));if(r()<st.cars*.28)carList.push({x:mx+seg.dx*(r()-.5)*seg.len*.55,z:mz+seg.dz*(r()-.5)*seg.len*.55,angle:-Math.atan2(seg.dz,seg.dx),seed:r()})}}return rendered}
function scatterTrees(list,pts,bounds,id,density){if(!density||+$('#detail').value===0)return;let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z)}minX=Math.max(minX,bounds.minX);maxX=Math.min(maxX,bounds.maxX);minZ=Math.max(minZ,bounds.minZ);maxZ=Math.min(maxZ,bounds.maxZ);const area=Math.max(0,(maxX-minX)*(maxZ-minZ)),limit=Math.min(+$('#detail').value===2?50:24,Math.floor(area/180*density));const r=rng(id+'trees');for(let i=0;i<limit*4&&list.length<limit;i++){const x=minX+r()*(maxX-minX),z=minZ+r()*(maxZ-minZ);if(pointInPoly(x,z,pts))list.push({x,z,s:.7+r()*.9})}}
function addTreeInstances(group,trees){if(!trees.length)return;const trunkGeo=new THREE.CylinderGeometry(.28,.42,3.4,6),leafGeo=new THREE.DodecahedronGeometry(1.8,0),trunks=new THREE.InstancedMesh(trunkGeo,shared.trunk,trees.length),leaves=new THREE.InstancedMesh(leafGeo,shared.leaf,trees.length),m=new THREE.Matrix4();trees.forEach((t,i)=>{m.compose(new THREE.Vector3(t.x,1.7*t.s,t.z),new THREE.Quaternion(),new THREE.Vector3(t.s,t.s,t.s));trunks.setMatrixAt(i,m);m.compose(new THREE.Vector3(t.x,4.2*t.s,t.z),new THREE.Quaternion(),new THREE.Vector3(t.s,t.s,t.s));leaves.setMatrixAt(i,m)});trunks.castShadow=leaves.castShadow=+$('#detail').value>0;group.add(trunks,leaves)}
function addLampInstances(group,lamps){if(!lamps.length||+$('#detail').value===0)return;const n=Math.min(lamps.length,80),pole=new THREE.InstancedMesh(new THREE.CylinderGeometry(.08,.12,4.2,5),shared.lamp,n),glow=new THREE.InstancedMesh(new THREE.SphereGeometry(.22,6,4),shared.lampGlow,n),m=new THREE.Matrix4();for(let i=0;i<n;i++){const p=lamps[i];m.makeTranslation(p.x,2.1,p.z);pole.setMatrixAt(i,m);m.makeTranslation(p.x,4.15,p.z);glow.setMatrixAt(i,m)}group.add(pole,glow)}
function addCars(group,cars){if(!cars.length||+$('#detail').value===0)return;const n=Math.min(cars.length,+$('#detail').value===2?28:14);for(let i=0;i<n;i++){const c=cars[i],body=new THREE.Mesh(new THREE.BoxGeometry(3.8,1.05,1.75),shared.car[Math.floor(c.seed*shared.car.length)%shared.car.length]);body.position.set(c.x,.68,c.z);body.rotation.y=c.angle;body.castShadow=true;group.add(body);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.8,.65,1.55),new THREE.MeshStandardMaterial({color:0x9db2b8,roughness:.35,metalness:.12}));cab.position.set(c.x,1.4,c.z);cab.rotation.y=c.angle;group.add(cab)}}
function renderChunk(c,data){const g=c.group,b=chunkBounds(c),areas=[],roads=[],buildings=[],trees=[],lamps=[],cars=[];for(const el of data.elements||[]){const t=el.tags||{};if(el.type==='node'){if(Number.isFinite(el.lat)&&Number.isFinite(el.lon)){const w=geoToWorld(el.lat,el.lon);if(inBounds(w.x,w.z,b)){if(t.natural==='tree')trees.push({x:w.x,z:w.z,s:.8+(hash(el.id)%50)/100});if(t.highway==='street_lamp')lamps.push(w)}}continue}if(t.building)buildings.push(el);else if(t.highway||t.railway||t.waterway)roads.push(el);else if(t.natural||t.landuse||t.leisure)areas.push(el)}let count=0;for(const el of areas)for(const q of geometries(el)){const pts=cleanPoints(q.geometry,true);if(pts.length<3)continue;const cen=centroid(pts),style=areaStyle(q.tags);if(inBounds(cen.x,cen.z,b)&&addArea(g,pts,style)){count++;c.features++}scatterTrees(trees,pts,b,q.id,style.trees)}for(const el of roads)for(const q of geometries(el)){const pts=cleanPoints(q.geometry,false);if(pts.length<2)continue;if(q.tags.waterway){for(let i=1;i<pts.length;i++){const a=pts[i-1],d=pts[i],m={x:(a.x+d.x)/2,z:(a.z+d.z)/2};if(inBounds(m.x,m.z,b,2))addSegmentBox(g,a,d,Math.max(2,parseFloat(q.tags.width)||3.5),shared.water,.035,.08)}count++;c.features++}else if(q.tags.railway){for(let i=1;i<pts.length;i++){const a=pts[i-1],d=pts[i],m={x:(a.x+d.x)/2,z:(a.z+d.z)/2};if(inBounds(m.x,m.z,b,2))addSegmentBox(g,a,d,2.2,shared.rail,.075,.11)}count++;c.features++}else{const n=renderRoad(g,pts,q.tags,b,cars);if(n){count++;c.features++}}}let built=0,limit=+$('#detail').value===0?160:+$('#detail').value===1?230:320;for(const el of buildings){if(built>=limit)break;for(const q of geometries(el)){if(built>=limit)break;const pts=cleanPoints(q.geometry,true);if(pts.length<4)continue;const cen=centroid(pts);if(!inBounds(cen.x,cen.z,b))continue;if(addBuilding(g,pts,q.tags,q.id)){built++;count++;c.features++}}}addTreeInstances(g,trees);addLampInstances(g,lamps);addCars(g,cars);if(c.pin){g.remove(c.pin);c.pin.geometry.dispose();c.pin.material.dispose();c.pin=null}c.state='ready';c.featureCount=count;totalFeatures+=count;updateStats()}
function openDB(){if(!('indexedDB'in window))return Promise.reject();if(dbPromise)return dbPromise;dbPromise=new Promise((res,rej)=>{const r=indexedDB.open('geovoxel-stream',1);r.onupgradeneeded=()=>r.result.createObjectStore('chunks');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbPromise}
async function cacheGet(k){try{const db=await openDB();return await new Promise((res,rej)=>{const r=db.transaction('chunks').objectStore('chunks').get(k);r.onsuccess=()=>{const v=r.result;res(v&&Date.now()-v.time<MAX_CACHE_AGE?v.data:null)};r.onerror=()=>rej(r.error)})}catch(e){return null}}
async function cachePut(k,data){try{const db=await openDB();await new Promise((res,rej)=>{const r=db.transaction('chunks','readwrite').objectStore('chunks').put({time:Date.now(),data},k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}catch(e){}}
function bboxFor(c){const h=CHUNK/2+OVERLAP,sw=worldToGeo(c.cx*CHUNK-h,c.cz*CHUNK-h),ne=worldToGeo(c.cx*CHUNK+h,c.cz*CHUNK+h);return{south:sw.lat,west:sw.lon,north:ne.lat,east:ne.lon}}
function queryFor(b){const x=`${b.south},${b.west},${b.north},${b.east}`;return`[out:json][timeout:26];(way["building"](${x});relation["building"](${x});way["highway"](${x});way["railway"](${x});way["waterway"](${x});way["natural"~"water|wood"](${x});relation["natural"~"water|wood"](${x});way["landuse"~"grass|forest|meadow|recreation_ground|village_green|cemetery|reservoir|basin|commercial|retail|industrial"](${x});relation["landuse"~"grass|forest|meadow|recreation_ground|village_green|cemetery|reservoir|basin|commercial|retail|industrial"](${x});way["leisure"~"park|garden|pitch|playground"](${x});relation["leisure"~"park|garden|pitch|playground"](${x});node["natural"="tree"](${x});node["highway"="street_lamp"](${x}););out geom;`}
async function fetchChunk(c,gen){const b=bboxFor(c),ck=`v3:${b.south.toFixed(5)}:${b.west.toFixed(5)}:${b.north.toFixed(5)}:${b.east.toFixed(5)}`,cached=await cacheGet(ck);if(cached)return{data:cached,cached:true};const q=queryFor(b),servers=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];let err;for(const s of servers){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),23000);try{const r=await fetch(s,{method:'POST',signal:ctrl.signal,headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8',Accept:'application/json'},body:'data='+encodeURIComponent(q)});clearTimeout(timer);if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(gen!==generation)throw Error('stale');if(!data||!Array.isArray(data.elements))throw Error('invalid response');cachePut(ck,data);return{data,cached:false}}catch(e){clearTimeout(timer);err=e}}throw err||Error('map request failed')}
function enqueue(c){if(c.state!=='new'&&c.state!=='error')return;c.state='queued';queue.push(c);sortQueue();pump();updateStats()}
function sortQueue(){const x=controls.target.x/CHUNK,z=controls.target.z/CHUNK;queue.sort((a,b)=>(a.cx-x)**2+(a.cz-z)**2-((b.cx-x)**2+(b.cz-z)**2))}
function pump(){if(active>=1||!queue.length)return;const c=queue.shift();if(!chunks.has(c.key)){pump();return}c.state='loading';active++;const gen=generation;statusEl.textContent=`Generating map chunk ${c.cx}, ${c.cz}…`;fetchChunk(c,gen).then(r=>{if(gen!==generation||!chunks.has(c.key))return;renderChunk(c,r.data);$('#source').textContent=r.cached?'cache':'OSM';statusEl.textContent='Streaming real map data. Pan toward an edge and new chunks will generate automatically.'}).catch(e=>{console.warn(e);if(gen===generation&&chunks.has(c.key)){c.state='error';if(c.pin)c.pin.material.color.set(0xe56b5d);statusEl.textContent='A map chunk failed to load. Pan onward or tap Retry; loaded chunks remain available.'}}).finally(()=>{active=Math.max(0,active-1);updateStats();setTimeout(pump,260)})}
function makeChunk(cx,cz){const key=chunkKey(cx,cz);if(chunks.has(key))return chunks.get(key);const c={key,cx,cz,state:'new',features:0,featureCount:0,group:new THREE.Group(),pin:null};c.group.name='chunk '+key;world.add(c.group);chunks.set(key,c);addChunkBase(c);enqueue(c);return c}
function desiredChunks(){const r=+$('#radius').value||1,cx=Math.round(controls.target.x/CHUNK),cz=Math.round(controls.target.z/CHUNK),want=new Set();for(let d=0;d<=r*2;d++)for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++)if(Math.abs(x)+Math.abs(z)===d){const k=chunkKey(cx+x,cz+z);want.add(k);makeChunk(cx+x,cz+z)}const unload=r+2;for(const[k,c]of[...chunks])if(Math.max(Math.abs(c.cx-cx),Math.abs(c.cz-cz))>unload){if(c.state==='ready')totalFeatures-=c.featureCount;disposeGroup(c.group);chunks.delete(k)}queue=queue.filter(c=>chunks.has(c.key));sortQueue();pump();return{cx,cz,want}}
function stream(ts){if(ts-lastStream<430)return;lastStream=ts;const s=desiredChunks(),key=s.cx+','+s.cz;if(key!==lastCenterKey){lastCenterKey=key;const g=worldToGeo(controls.target.x,controls.target.z);$('#coords').textContent=`Center: ${g.lat.toFixed(5)}, ${g.lon.toFixed(5)} · chunk ${key}`;$('#osm').href=`https://www.openstreetmap.org/#map=18/${g.lat}/${g.lon}`;updateStats()}}
function updateStats(){let ready=0,failed=0;for(const c of chunks.values()){if(c.state==='ready')ready++;if(c.state==='error')failed++}$('#loaded').textContent=ready;$('#queued').textContent=queue.length+active;$('#features').textContent=Math.max(0,totalFeatures);if(failed)$('#source').textContent=failed+' err'}
function setMode(pan){panMode=pan;controls.enableRotate=!pan;controls.mouseButtons.LEFT=pan?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;controls.touches.ONE=pan?THREE.TOUCH.PAN:THREE.TOUCH.ROTATE;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;$('#mode').textContent=pan?'Pan mode':'Orbit mode';$('#mode').classList.toggle('active',pan);$('#help').textContent=pan?'Pan mode: drag to travel · pinch to zoom · chunks generate around the center':'Orbit mode: drag to rotate · two-finger drag to travel';toast(pan?'Drag with one finger to travel':'Drag to orbit; use two fingers to travel')}
function resetView(){const g=worldToGeo(controls.target.x,controls.target.z);camera.position.set(controls.target.x+205,175,controls.target.z+235);controls.target.set(controls.target.x,8,controls.target.z);controls.update();$('#osm').href=`https://www.openstreetmap.org/#map=18/${g.lat}/${g.lon}`}
function startLocation(){const lat=parseFloat($('#lat').value),lon=parseFloat($('#lon').value);if(!Number.isFinite(lat)||!Number.isFinite(lon)){statusEl.textContent='Enter valid coordinates.';return}origin={lat,lon};clearWorld();controls.target.set(0,8,0);lastCenterKey='';resetView();$('#osm').href=`https://www.openstreetmap.org/#map=18/${lat}/${lon}`;statusEl.textContent='Starting the streaming world…';desiredChunks()}
function retryErrors(){for(const c of chunks.values())if(c.state==='error')enqueue(c);toast('Retrying failed chunks')}
function compass(){const d=new THREE.Vector3();camera.getWorldDirection(d);const angle=Math.atan2(d.x,d.z);$('#needle').style.transform=`rotate(${angle}rad)`}
$('#preset').onchange=e=>{const[a,b]=e.target.value.split(',');$('#lat').value=a;$('#lon').value=b};$('#go').onclick=startLocation;$('#locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('#lat').value=p.coords.latitude.toFixed(6);$('#lon').value=p.coords.longitude.toFixed(6);startLocation()},()=>statusEl.textContent='Location permission was not granted.',{enableHighAccuracy:true,timeout:12000}):statusEl.textContent='Geolocation is unavailable.';$('#mode').onclick=()=>setMode(!panMode);$('#reset').onclick=resetView;$('#retry').onclick=retryErrors;$('#radius').onchange=()=>desiredChunks();$('#detail').onchange=()=>{toast('Detail applies to newly generated chunks');retryErrors()};$('#voxel').onchange=()=>toast('Voxel size applies to newly generated chunks');
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setAnimationLoop(t=>{controls.update();stream(t);compass();renderer.render(scene,camera)});setMode(true);resetView();loadingEl.hidden=true;startLocation();
})();