(()=>{
'use strict';
const G=window.GeoVoxel={};
G.$=s=>document.querySelector(s);
G.MOBILE=/iPad|iPhone|Android/i.test(navigator.userAgent);
G.CFG={CHUNK:160,VECTOR_Z:15,TERRAIN_Z:13,TILE_PX:256,CACHE_AGE:7*86400000,MAX_ACTIVE:G.MOBILE?3:5};
G.state={origin:{lat:45.5231,lon:-122.6765},baseElev:0,chunks:new Map(),queue:[],active:0,generation:0,totalFeatures:0,lastStream:0,lastCenterKey:'',tileTemplate:null,dbPromise:null,requestCounter:0,facades:new Set(),flightFocus:null};
G.status=G.$('#status');G.loading=G.$('#loading');
if(!window.THREE){G.loading.innerHTML='<div><h2>Could not load Three.js</h2><p>Reload with an internet connection.</p></div>';G.failed=true;return}
const scene=G.scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc3d4);scene.fog=new THREE.Fog(0x9fc3d4,420,1450);
const camera=G.camera=new THREE.PerspectiveCamera(56,innerWidth/innerHeight,.1,3200);
const renderer=G.renderer=new THREE.WebGLRenderer({canvas:G.$('#view'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,G.MOBILE?1.35:1.85));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;
const controls=G.controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.maxPolarAngle=Math.PI*.485;controls.minDistance=20;controls.maxDistance=1300;controls.screenSpacePanning=false;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};controls.keyPanSpeed=28;if(controls.listenToKeyEvents)controls.listenToKeyEvents(window);
const hemi=G.hemi=new THREE.HemisphereLight(0xecfaff,0x4b5c43,1.78);scene.add(hemi);
const sun=G.sun=new THREE.DirectionalLight(0xffefd0,1.52);sun.position.set(-260,360,180);sun.castShadow=true;sun.shadow.mapSize.set(G.MOBILE?1024:2048,G.MOBILE?1024:2048);sun.shadow.camera.left=-500;sun.shadow.camera.right=500;sun.shadow.camera.top=500;sun.shadow.camera.bottom=-500;sun.shadow.bias=-.0008;scene.add(sun);
G.world=new THREE.Group();scene.add(G.world);
G.hash=v=>{let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
G.rng=seed=>{let s=G.hash(seed)||1;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)};
G.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
G.lerp=(a,b,t)=>a+(b-a)*t;
G.parseMeters=v=>{if(v==null)return NaN;const s=String(v).trim(),n=parseFloat(s);if(!Number.isFinite(n))return NaN;return /ft|feet|foot|'/i.test(s)?n*.3048:n};
G.geoToWorld=(lat,lon)=>({x:(lon-G.state.origin.lon)*111320*Math.cos(G.state.origin.lat*Math.PI/180),z:(lat-G.state.origin.lat)*110540});
G.worldToGeo=(x,z)=>({lat:G.state.origin.lat+z/110540,lon:G.state.origin.lon+x/(111320*Math.cos(G.state.origin.lat*Math.PI/180))});
G.chunkKey=(x,z)=>`${x},${z}`;
G.chunkBounds=c=>{const h=G.CFG.CHUNK/2;return{minX:c.cx*G.CFG.CHUNK-h,maxX:c.cx*G.CFG.CHUNK+h,minZ:c.cz*G.CFG.CHUNK-h,maxZ:c.cz*G.CFG.CHUNK+h}};
G.inBounds=(x,z,b,p=0)=>x>=b.minX-p&&x<=b.maxX+p&&z>=b.minZ-p&&z<=b.maxZ+p;
G.centroid=pts=>{let x=0,z=0;for(const p of pts){x+=p.x;z+=p.z}return{x:x/(pts.length||1),z:z/(pts.length||1)}};
G.boundsOf=pts=>{let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z)}return{minX,maxX,minZ,maxZ,x:(minX+maxX)/2,z:(minZ+maxZ)/2,w:maxX-minX,d:maxZ-minZ}};
G.pointInPoly=(x,z,p)=>{let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a.z>z)!=(b.z>z))&&(x<(b.x-a.x)*(z-a.z)/(b.z-a.z+1e-9)+a.x))inside=!inside}return inside};
G.makeShape=pts=>{if(pts.length<3)return null;const p=pts.slice(),a=p[0],b=p[p.length-1];if(Math.hypot(a.x-b.x,a.z-b.z)<.2)p.pop();if(p.length<3)return null;const s=new THREE.Shape();s.moveTo(p[0].x,-p[0].z);for(let i=1;i<p.length;i++)s.lineTo(p[i].x,-p[i].z);s.closePath();return s};
G.snap=(v,lod=0)=>{const base=Number(G.$('#voxel').value)||2,step=lod===0?base:lod===1?Math.max(3,base*2):Math.max(8,base*4);return Math.round(v/step)*step};
G.cleanPoints=(pts,lod=0,closed=false)=>{const out=[];for(const p of pts||[]){const w=p.x!=null?p:G.geoToWorld(p.lat,p.lon),q={x:G.snap(w.x,lod),z:G.snap(w.z,lod)};const prev=out[out.length-1];if(!prev||Math.hypot(q.x-prev.x,q.z-prev.z)>.15)out.push(q)}if(closed&&out.length>2){const a=out[0],b=out[out.length-1];if(Math.hypot(a.x-b.x,a.z-b.z)>.15)out.push({...a})}return out};
G.disposeObject=o=>{if(!o)return;o.traverse?.(n=>{n.geometry?.dispose();if(n.userData?.ownedMaterial){const arr=Array.isArray(n.material)?n.material:[n.material];arr.forEach(m=>{m.map?.dispose?.();m.emissiveMap?.dispose?.();m.dispose?.()})}});o.parent?.remove(o)};
G.setOpacity=(group,value)=>group.traverse(o=>{if(!o.material)return;let mats=Array.isArray(o.material)?o.material:[o.material];if(!o.userData.fadeOwned){mats=mats.map(m=>m.clone());o.material=Array.isArray(o.material)?mats:mats[0];o.userData.fadeOwned=true;o.userData.ownedMaterial=true;for(const m of mats)if(m.userData?.isFacade)G.state.facades.add(m)}for(const m of mats){m.transparent=value<.999||m.transparent;m.opacity=value;m.depthWrite=value>.65}});
G.fadeIn=group=>{group.userData.fade={from:0,to:1,start:performance.now(),duration:420};G.setOpacity(group,0)};
G.fadeOut=(group,onDone)=>{group.userData.fade={from:1,to:0,start:performance.now(),duration:300,onDone}};
G.updateFades=time=>{G.world.traverse(o=>{const f=o.userData?.fade;if(!f)return;const t=G.clamp((time-f.start)/f.duration,0,1),e=t*t*(3-2*t);G.setOpacity(o,G.lerp(f.from,f.to,e));if(t>=1){delete o.userData.fade;if(f.onDone)f.onDone()}})};
G.toast=text=>{const e=G.$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(G.toastTimer);G.toastTimer=setTimeout(()=>e.classList.remove('show'),2600)};
G.shared={terrain:new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true,side:THREE.DoubleSide}),road:{},area:{},building:{},water:new THREE.MeshStandardMaterial({color:0x5fa4c4,roughness:.25,metalness:.06,transparent:true,opacity:.88,side:THREE.DoubleSide}),sidewalk:new THREE.MeshStandardMaterial({color:0xaaa495,roughness:1}),marking:new THREE.MeshBasicMaterial({color:0xeee2b9}),rail:new THREE.MeshStandardMaterial({color:0x43484b,roughness:1}),trunk:new THREE.MeshStandardMaterial({color:0x6d5038,roughness:1}),leaf:new THREE.MeshStandardMaterial({color:0x477b4b,roughness:1,flatShading:true}),lamp:new THREE.MeshStandardMaterial({color:0x485156,roughness:.8,metalness:.15}),lampGlow:new THREE.MeshBasicMaterial({color:0xffe4a0}),roof:new THREE.MeshStandardMaterial({color:0x706c65,roughness:.92,flatShading:true})};
G.material=(store,color,extra={})=>{const key=`${color}:${JSON.stringify(extra)}`;return store[key]||(store[key]=new THREE.MeshStandardMaterial({color,roughness:.9,...extra}))};
G.roadMat=c=>G.material(G.shared.road,c,{polygonOffset:true,polygonOffsetFactor:-2});G.areaMat=c=>G.material(G.shared.area,c,{side:THREE.DoubleSide});G.buildingMat=c=>G.material(G.shared.building,c,{flatShading:true});
G.windowTexture=(()=>{const c=document.createElement('canvas');c.width=128;c.height=128;const x=c.getContext('2d');x.fillStyle='#303a3b';x.fillRect(0,0,128,128);for(let y=7;y<128;y+=22)for(let q=7;q<128;q+=22){const warm=((q+y)/22)%3===0;x.fillStyle=warm?'#d6b66e':'#87a8ad';x.fillRect(q,y,13,12);x.fillStyle='#1d2729';x.fillRect(q+6,y,1,12)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1,1);t.magFilter=THREE.NearestFilter;return t})();
G.facadeMaterial=color=>{const m=new THREE.MeshStandardMaterial({color,map:G.windowTexture,emissive:0x6b5428,emissiveMap:G.windowTexture,emissiveIntensity:0,roughness:.82});G.state.facades.add(m);return m};
G.getFocus=()=>G.state.flightFocus||{x:controls.target.x,z:controls.target.z};
G.clearWorld=()=>{G.state.generation++;G.state.queue=[];G.state.active=0;for(const c of G.state.chunks.values())G.disposeObject(c.group);G.state.chunks.clear();G.state.totalFeatures=0};
G.resetView=()=>{const f=G.getFocus();camera.position.set(f.x+210,175,f.z+235);controls.target.set(f.x,8,f.z);controls.update()};
G.TIME_KEYS=[{h:0,sky:0x071326,hemi:.28,sunI:0,sunC:0x8fb4ff},{h:5,sky:0x18243a,hemi:.4,sunI:.05,sunC:0xffb37c},{h:6.5,sky:0xdfa67d,hemi:.95,sunI:.72,sunC:0xffa365},{h:9,sky:0x9fc3d4,hemi:1.62,sunI:1.38,sunC:0xffefd0},{h:13,sky:0xa4cbdc,hemi:1.78,sunI:1.52,sunC:0xfff3da},{h:18.8,sky:0xdc8f67,hemi:.85,sunI:.58,sunC:0xff9557},{h:20.7,sky:0x1a2740,hemi:.42,sunI:.05,sunC:0xffb37c},{h:24,sky:0x071326,hemi:.28,sunI:0,sunC:0x8fb4ff}];
G.applyTime=hours=>{let a=G.TIME_KEYS[0],b=G.TIME_KEYS.at(-1);for(let i=0;i<G.TIME_KEYS.length-1;i++)if(hours>=G.TIME_KEYS[i].h&&hours<=G.TIME_KEYS[i+1].h){a=G.TIME_KEYS[i];b=G.TIME_KEYS[i+1];break}const t=(hours-a.h)/(b.h-a.h||1),sky=new THREE.Color(a.sky).lerp(new THREE.Color(b.sky),t);scene.background=sky;scene.fog.color.copy(sky);hemi.intensity=G.lerp(a.hemi,b.hemi,t);sun.intensity=G.lerp(a.sunI,b.sunI,t);sun.color.set(new THREE.Color(a.sunC).lerp(new THREE.Color(b.sunC),t));const az=hours/24*Math.PI*2-Math.PI/2,el=Math.max(.08,Math.sin((hours-6)/12*Math.PI));sun.position.set(Math.cos(az)*480*(1-el*.35),480*el,Math.sin(az)*480*(1-el*.35));sun.castShadow=sun.intensity>.15;const night=1-Math.min(1,sun.intensity/.65);for(const m of G.state.facades)m.emissiveIntensity=night*1.15;const hh=Math.floor(hours),mm=Math.round((hours-hh)*60);G.$('#timeread').textContent=`${String(hh%24).padStart(2,'0')}:${String(mm).padStart(2,'0')}`};
G.updateCompass=()=>{const d=new THREE.Vector3();camera.getWorldDirection(d);G.$('#needle').style.transform=`rotate(${Math.atan2(d.x,d.z)}rad)`};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
})();
