(()=>{
'use strict';
const G=window.GeoVoxel;if(!G||G.failed)return;const S=G.state;
const bird=(()=>{const g=new THREE.Group(),grey=new THREE.MeshStandardMaterial({color:0x8d939c,roughness:.82}),dark=new THREE.MeshStandardMaterial({color:0x565b63,roughness:.82}),neck=new THREE.MeshStandardMaterial({color:0x50775f,roughness:.55,metalness:.25}),orange=new THREE.MeshStandardMaterial({color:0xd88940,roughness:.75});const body=new THREE.Mesh(new THREE.BoxGeometry(1.7,.95,.95),grey);body.castShadow=true;g.add(body);const chest=new THREE.Mesh(new THREE.BoxGeometry(.62,.72,.82),neck);chest.position.set(.72,.1,0);g.add(chest);const head=new THREE.Mesh(new THREE.BoxGeometry(.56,.56,.56),grey);head.position.set(1.12,.55,0);g.add(head);const beak=new THREE.Mesh(new THREE.ConeGeometry(.14,.45,5),orange);beak.rotation.z=-Math.PI/2;beak.position.set(1.52,.5,0);g.add(beak);const tail=new THREE.Mesh(new THREE.BoxGeometry(.95,.1,.55),dark);tail.position.set(-1.05,.2,0);tail.rotation.z=.28;g.add(tail);const lg=new THREE.BoxGeometry(.95,.08,1.55);lg.translate(0,0,.82);const rg=new THREE.BoxGeometry(.95,.08,1.55);rg.translate(0,0,-.82);const left=new THREE.Mesh(lg,dark),right=new THREE.Mesh(rg,dark);left.position.set(.1,.32,.3);right.position.set(.1,.32,-.3);g.add(left,right);g.scale.setScalar(1.8);g.rotation.order='YZX';g.visible=false;G.scene.add(g);return{group:g,left,right}})();
const F=G.flight={on:false,pov:false,heading:0,pitch:0,speed:34,turn:0,rise:0,pos:new THREE.Vector3(),last:performance.now()};
const setSpeed=v=>{F.speed=G.clamp(v,10,95);G.$('#spd').textContent=`${Math.round(F.speed)} m/s`};
G.setPov=on=>{F.pov=on;G.$('#pov').classList.toggle('active',on);bird.group.visible=F.on&&!on;if(F.on)G.toast(on?'Pigeon POV':'Chase camera')};
G.setFly=on=>{F.on=on;G.controls.enabled=!on;G.$('#fly').textContent=on?'Land':'🕊 Fly';G.$('#fly').classList.toggle('active',on);G.$('#flyui').classList.toggle('on',on);if(on){const x=G.controls.target.x,z=G.controls.target.z;F.pos.set(x,Math.max(G.elevAtWorld(x,z)+38,G.controls.target.y+28),z);const d=new THREE.Vector3();G.camera.getWorldDirection(d);F.heading=Math.atan2(d.z,d.x);F.pitch=F.turn=F.rise=0;S.flightFocus={x:F.pos.x,z:F.pos.z};bird.group.visible=!F.pov;G.$('#help').textContent='Fly: drag to steer · arrows/WASD turn and climb · +/− speed · POV for first person';G.toast('The sharp voxel ring now follows the pigeon')}else{S.flightFocus=null;S.flightExtra=0;bird.group.visible=false;G.controls.target.set(F.pos.x,8,F.pos.z);G.camera.position.set(F.pos.x+190,165,F.pos.z+220);G.controls.update();G.$('#help').textContent='Drag to orbit · two-finger drag to travel · scroll/pinch to zoom'}};
const keys={};const updateKeys=()=>{F.turn=(keys.arrowright||keys.d?1:0)-(keys.arrowleft||keys.a?1:0);F.rise=(keys.arrowup||keys.w?1:0)-(keys.arrowdown||keys.s?1:0)};
addEventListener('keydown',e=>{if(!F.on||e.target.tagName==='INPUT')return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))e.preventDefault();keys[k]=true;if(k==='+'||k==='=')setSpeed(F.speed+8);if(k==='-'||k==='_')setSpeed(F.speed-8);if(k==='v')G.setPov(!F.pov);updateKeys()});addEventListener('keyup',e=>{if(!F.on)return;keys[e.key.toLowerCase()]=false;updateKeys()});
let steer=null;const canvas=G.renderer.domElement;canvas.addEventListener('pointerdown',e=>{if(!F.on)return;steer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!F.on||!steer||e.pointerId!==steer.id)return;F.turn=G.clamp((e.clientX-steer.x)/110,-1,1);F.rise=G.clamp((steer.y-e.clientY)/110,-1,1)});const end=e=>{if(steer&&e.pointerId===steer.id){steer=null;F.turn=F.rise=0}};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
G.updateFlight=time=>{if(!F.on){F.last=time;return}const dt=Math.min(.08,Math.max(.001,(time-F.last)/1000));F.last=time;F.heading+=F.turn*1.7*dt;F.pitch=G.clamp(F.pitch+F.rise*1.5*dt,-.95,.95);if(!F.rise)F.pitch*=Math.pow(.25,dt);const cp=Math.cos(F.pitch),ch=Math.cos(F.heading),sh=Math.sin(F.heading);F.pos.x+=ch*cp*F.speed*dt;F.pos.z+=sh*cp*F.speed*dt;F.pos.y+=Math.sin(F.pitch)*F.speed*dt;const floor=G.elevAtWorld(F.pos.x,F.pos.z)+2.7;if(F.pos.y<floor){F.pos.y=floor;if(F.pitch<0)F.pitch=0}F.pos.y=Math.min(520,F.pos.y);S.flightFocus.x=F.pos.x;S.flightFocus.z=F.pos.z;S.flightExtra=F.pos.y>140?1:0;bird.group.position.copy(F.pos);bird.group.rotation.y=-F.heading;bird.group.rotation.z=F.pitch*.7;bird.group.rotation.x=THREE.MathUtils.lerp(bird.group.rotation.x,-F.turn*.5,Math.min(1,dt*6));const flap=Math.sin(time/1000*(7+F.speed*.06))*.55;bird.left.rotation.x=-flap;bird.right.rotation.x=flap;G.controls.target.set(F.pos.x,F.pos.y,F.pos.z);if(F.pov){const desired=new THREE.Vector3(F.pos.x+ch*1.5,F.pos.y+1.3,F.pos.z+sh*1.5);G.camera.position.lerp(desired,1-Math.pow(.0001,dt));G.camera.lookAt(F.pos.x+ch*cp*50,F.pos.y+1.3+Math.sin(F.pitch)*50,F.pos.z+sh*cp*50)}else{const back=16+F.speed*.14,desired=new THREE.Vector3(F.pos.x-ch*back,F.pos.y+6.5,F.pos.z-sh*back);G.camera.position.lerp(desired,1-Math.pow(.002,dt));G.camera.lookAt(F.pos.x,F.pos.y+1.5,F.pos.z)}};
G.$('#spdDown').onclick=()=>setSpeed(F.speed-8);G.$('#spdUp').onclick=()=>setSpeed(F.speed+8);G.$('#pov').onclick=()=>G.setPov(!F.pov);setSpeed(F.speed);
})();
