(()=>{
'use strict';
const G=window.GeoVoxel;if(!G||G.failed)return;
const TD=new TextDecoder();
const varint=(v,s)=>{let r=0,sh=0,b;do{if(s.p>=v.byteLength)throw new Error('PBF overflow');b=v.getUint8(s.p++);r+=(b&127)*2**sh;sh+=7}while(b&128);return r};
const skip=(v,s,wt)=>{if(wt===0)varint(v,s);else if(wt===1)s.p+=8;else if(wt===2)s.p+=varint(v,s);else if(wt===5)s.p+=4;else throw new Error(`Unknown PBF wire ${wt}`)};
const str=(v,s,n)=>{const a=new Uint8Array(v.buffer,v.byteOffset+s.p,n);s.p+=n;return TD.decode(a)};
const zig=n=>n%2?-(n+1)/2:n/2;
const value=(v,start,end)=>{const s={p:start};while(s.p<end){const tag=varint(v,s),f=tag>>3,wt=tag&7;if(f===1&&wt===2){const n=varint(v,s);return str(v,s,n)}if(f===2&&wt===5){const x=v.getFloat32(s.p,true);s.p+=4;return x}if(f===3&&wt===1){const x=v.getFloat64(s.p,true);s.p+=8;return x}if(f===4&&wt===0)return varint(v,s);if(f===5&&wt===0)return varint(v,s);if(f===6&&wt===0)return zig(varint(v,s));if(f===7&&wt===0)return!!varint(v,s);skip(v,s,wt)}return null};
const feature=(v,start,end,keys,vals)=>{const s={p:start},out={id:0,type:0,props:{},raw:null};while(s.p<end){const tag=varint(v,s),f=tag>>3,wt=tag&7;if(f===1&&wt===0)out.id=varint(v,s);else if(f===2&&wt===2){const n=varint(v,s),stop=s.p+n;while(s.p<stop){const k=varint(v,s),x=varint(v,s);if(keys[k]!=null)out.props[keys[k]]=vals[x]}}else if(f===3&&wt===0)out.type=varint(v,s);else if(f===4&&wt===2){const n=varint(v,s),stop=s.p+n,raw=[];while(s.p<stop)raw.push(varint(v,s));out.raw=raw}else skip(v,s,wt)}return out};
const geometry=raw=>{const rings=[];let ring=null,x=0,y=0,i=0;while(i<raw.length){const cmd=raw[i++],op=cmd&7,count=Math.floor(cmd/8);if(op===1){for(let k=0;k<count;k++){if(ring?.length)rings.push(ring);ring=[];x+=zig(raw[i++]);y+=zig(raw[i++]);ring.push([x,y])}}else if(op===2){for(let k=0;k<count;k++){x+=zig(raw[i++]);y+=zig(raw[i++]);ring.push([x,y])}}else if(op===7){if(ring?.length)ring.push(ring[0].slice())}else break}if(ring?.length)rings.push(ring);return rings};
G.decodeMVT=buffer=>{const v=new DataView(buffer),s={p:0},layers={};while(s.p<buffer.byteLength){const tag=varint(v,s),f=tag>>3,wt=tag&7;if(f!==3||wt!==2){skip(v,s,wt);continue}const n=varint(v,s),stop=s.p+n,layer={name:'',extent:4096,ranges:[],keys:[],values:[]};while(s.p<stop){const t=varint(v,s),ff=t>>3,ww=t&7;if(ff===1&&ww===2){const l=varint(v,s);layer.name=str(v,s,l)}else if(ff===2&&ww===2){const l=varint(v,s);layer.ranges.push([s.p,s.p+l]);s.p+=l}else if(ff===3&&ww===2){const l=varint(v,s);layer.keys.push(str(v,s,l))}else if(ff===4&&ww===2){const l=varint(v,s);layer.values.push(value(v,s.p,s.p+l));s.p+=l}else if(ff===5&&ww===0)layer.extent=varint(v,s);else skip(v,s,ww)}layer.features=layer.ranges.map(([a,b])=>feature(v,a,b,layer.keys,layer.values));layers[layer.name]=layer}return layers};
const signedArea=r=>{let a=0;for(let i=0,j=r.length-1;i<r.length;j=i++)a+=(r[j][0]-r[i][0])*(r[j][1]+r[i][1]);return a/2};
const ROAD={motorway:'motorway',trunk:'trunk',primary:'primary',secondary:'secondary',tertiary:'tertiary',minor:'residential',service:'service',track:'service',raceway:'service',busway:'service',path:'footway',pier:'footway'};
const areaTags=(name,p)=>{const c=p.class||'',s=p.subclass||'';if(name==='water')return{natural:'water'};if(name==='park')return{leisure:'park'};if(name==='landcover'){if(['wood','forest'].includes(c)||s==='forest')return{natural:'wood'};if(['grass','grassland','meadow'].includes(c))return{landuse:'grass'};return null}if(name==='landuse'){if(['commercial','retail','industrial','cemetery'].includes(c))return{landuse:c};if(['pitch','stadium','playground'].includes(c))return{leisure:'pitch'};return null}return null};
G.parseVectorTile=(layers,z,x,y)=>{const n=2**z,toGeo=(px,py,e)=>({lon:(x+px/e)/n*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*(y+py/e)/n)))*180/Math.PI}),groups={buildings:[],roads:[],rails:[],waterLines:[],areas:[]};
 const polygons=(layer,tagsFn)=>{const out=[];for(const f of layer.features){if(f.type!==3||!f.raw)continue;const tags=tagsFn(f.props);if(!tags)continue;const rings=geometry(f.raw);let outer=0,best=0;for(const r of rings){const a=signedArea(r);if(Math.abs(a)>best){best=Math.abs(a);outer=Math.sign(a)}}rings.forEach((r,i)=>{if(r.length<4||Math.sign(signedArea(r))!==outer)return;const pts=r.map(([px,py])=>toGeo(px,py,layer.extent));let lat=0,lon=0;for(const p of pts){lat+=p.lat;lon+=p.lon}out.push({pts,tags,id:`${layer.name}:${f.id||G.hash(r[0])}:${i}`,c:{lat:lat/pts.length,lon:lon/pts.length}})})}return out};
 const bl=layers.building;if(bl)groups.buildings=polygons(bl,p=>({building:'yes',height:p.render_height!=null?String(p.render_height):p.height!=null?String(p.height):undefined,min_height:p.render_min_height!=null?String(p.render_min_height):undefined,'building:colour':typeof p.colour==='string'?p.colour:undefined}));
 const tr=layers.transportation;if(tr)for(const f of tr.features){if(f.type!==2||!f.raw)continue;const cls=f.props.class||'',lines=geometry(f.raw).map(l=>l.map(([px,py])=>toGeo(px,py,tr.extent)));if(cls==='rail'||cls==='transit'){for(const pts of lines)groups.rails.push({pts,tags:{railway:'rail'},id:`rail:${f.id}`})}else if(ROAD[cls]){const tags={highway:ROAD[cls]};if(f.props.brunnel==='bridge')tags.bridge='yes';if(f.props.layer!=null)tags.layer=String(f.props.layer);for(const pts of lines)groups.roads.push({pts,tags,id:`road:${f.id}`})}}
 const ww=layers.waterway;if(ww)for(const f of ww.features){if(f.type!==2||!f.raw)continue;for(const l of geometry(f.raw)){groups.waterLines.push({pts:l.map(([px,py])=>toGeo(px,py,ww.extent)),tags:{waterway:f.props.class||'stream'},id:`waterway:${f.id}`})}}
 for(const name of['water','park','landcover','landuse']){const l=layers[name];if(l)groups.areas.push(...polygons(l,p=>areaTags(name,p)))}
 return groups};
})();
