(()=>{
'use strict';
const G=window.GeoVoxel;if(!G||G.failed)return;
const palette=[0xd8c59f,0xc9ad83,0xbcc0b8,0xc58e77,0xddd3bd,0xa5aca4,0xc7bba7,0xb9a78e];
const pushTri=(p,c,a,b,d)=>{for(const v of[a,b,d]){p.push(v[0],v[1],v[2]);c.push(v[3][0],v[3][1],v[3][2])}};
const pushQuad=(p,c,a,b,d,e,col)=>{const A=[...a,col],B=[...b,col],D=[...d,col],E=[...e,col];pushTri(p,c,A,B,D);pushTri(p,c,A,D,E)};
const topColor=(h,rough)=>{const low=new THREE.Color(0x79906d),high=new THREE.Color(0xa7a780),rock=new THREE.Color(0x80776c),t=G.clamp((h+35)/160,0,1);const base=low.clone().lerp(high,t*.55);return rough>5?base.lerp(rock,G.clamp((rough-5)/16,0,.75)):base};
G.makeTerracedTerrain=(c,lod)=>{const b=G.chunkBounds(c),quality=Number(G.$('#detail').value),n=lod===0?(quality===2?30:quality===1?24:18):lod===1?13:7,cell=G.CFG.CHUNK/n,h=[];for(let z=0;z<n;z++){h[z]=[];for(let x=0;x<n;x++){const wx=b.minX+(x+.5)*cell,wz=b.minZ+(z+.5)*cell;h[z][x]=G.voxelElev(wx,wz,lod)}}let min=Infinity;for(const row of h)for(const v of row)min=Math.min(min,v);const base=min-Math.max(4,Number(G.$('#voxel').value)*2),pos=[],cols=[];
 for(let z=0;z<n;z++)for(let x=0;x<n;x++){const x0=b.minX+x*cell,x1=x0+cell,z0=b.minZ+z*cell,z1=z0+cell,y=h[z][x],neighbors=[z?h[z-1][x]:base,x<n-1?h[z][x+1]:base,z<n-1?h[z+1][x]:base,x?h[z][x-1]:base],rough=Math.max(...neighbors.map(q=>Math.abs(y-q))),tc=topColor(y,rough),top=[tc.r,tc.g,tc.b],side=new THREE.Color(0x756b5e).lerp(tc,.28),sc=[side.r,side.g,side.b];pushQuad(pos,cols,[x0,y,z0],[x0,y,z1],[x1,y,z1],[x1,y,z0],top);if(y>neighbors[0]+.01)pushQuad(pos,cols,[x0,neighbors[0],z0],[x1,neighbors[0],z0],[x1,y,z0],[x0,y,z0],sc);if(y>neighbors[1]+.01)pushQuad(pos,cols,[x1,neighbors[1],z0],[x1,neighbors[1],z1],[x1,y,z1],[x1,y,z0],sc);if(y>neighbors[2]+.01)pushQuad(pos,cols,[x1,neighbors[2],z1],[x0,neighbors[2],z1],[x0,y,z1],[x1,y,z1],sc);if(y>neighbors[3]+.01)pushQuad(pos,cols,[x0,neighbors[3],z1],[x0,neighbors[3],z0],[x0,y,z0],[x0,y,z1],sc)}
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,G.shared.terrain);mesh.receiveShadow=lod<2;mesh.castShadow=lod===0&&!G.MOBILE;return mesh};
const areaStyle=t=>{if(t.natural==='water')return{color:0x5fa4c4,water:true,trees:0};if(t.natural==='wood')return{color:0x4f7a51,trees:1};if(t.leisure==='park')return{color:0x67936a,trees:.5};if(t.leisure==='pitch')return{color:0x73936d,trees:0};if(['grass','cemetery'].includes(t.landuse))return{color:0x77956d,trees:.18};if(['commercial','retail'].includes(t.landuse))return{color:0x9b8f82,trees:0};if(t.landuse==='industrial')return{color:0x8c8a82,trees:0};return{color:0x829775,trees:0}};
const roadStyle=(t,lod)=>{const h=t.highway||'';let s;if(['motorway','trunk'].includes(h))s={width:12,color:0x48535a,walk:0,mark:1};else if(['primary','secondary'].includes(h))s={width:9,color:0x525e64,walk:1,mark:1};else if(h==='tertiary')s={width:7.5,color:0x576268,walk:1,mark:1};else if(['residential','unclassified'].includes(h))s={width:6.2,color:0x5d676c,walk:1,mark:0};else if(h==='service')s={width:4.5,color:0x666e72,walk:.5,mark:0};else s={width:2.2,color:0x9d927b,walk:0,mark:0};if(lod>0){s.walk=0;s.mark=0;if(lod===2)s.width=Math.max(4,Math.round(s.width/4)*4)}return s};
const geoWorld=(pts,lod,closed=false)=>G.cleanPoints(pts.map(p=>G.geoToWorld(p.lat,p.lon)),lod,closed);
const areaMesh=(pts,style,lod)=>{const shape=G.makeShape(pts);if(!shape)return null;try{const geo=new THREE.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;if(style.water){let min=Infinity;for(const p of pts)min=Math.min(min,G.voxelElev(p.x,p.z,lod));for(let i=0;i<pos.count;i++)pos.setY(i,min+.18)}else for(let i=0;i<pos.count;i++)pos.setY(i,G.voxelElev(pos.getX(i),pos.getZ(i),lod)+.15);geo.computeVertexNormals();const m=new THREE.Mesh(geo,style.water?G.shared.water:G.areaMat(style.color));m.receiveShadow=lod<2;return m}catch{return null}};
const buildingHeight=(t,id,lod)=>{let h=G.parseMeters(t.height);if(!Number.isFinite(h))h=5.5+Math.pow((G.hash(id)%1000)/1000,1.55)*28;const step=lod===0?Number(G.$('#voxel').value):lod===1?3:8;return Math.max(step*2,Math.round(G.clamp(h,3,300)/step)*step)};
const buildingColor=(t,id,lod)=>{const c=t['building:colour'];let x=c&&/^#?[0-9a-f]{6}$/i.test(c)?parseInt(c.replace('#',''),16):palette[G.hash(id)%palette.length];if(lod===2){const q=new THREE.Color(x);q.lerp(new THREE.Color(0xb9b29f),.3);x=q.getHex()}return x};
const addSegment=(group,a,b,width,mat,lift=.12,height=.14)=>{const dx=b.x-a.x,dz=b.z-a.z,dy=b.y-a.y,flat=Math.hypot(dx,dz);if(flat<.3)return null;const len=Math.hypot(flat,dy),m=new THREE.Mesh(new THREE.BoxGeometry(len,height,width),mat);m.position.set((a.x+b.x)/2,(a.y+b.y)/2+lift,(a.z+b.z)/2);m.rotation.order='YZX';m.rotation.y=-Math.atan2(dz,dx);m.rotation.z=Math.atan2(dy,flat);m.receiveShadow=true;group.add(m);return{len,dx:dx/flat,dz:dz/flat,x:m.position.x,z:m.position.z}};
const addRoad=(group,f,bounds,lod,lamps)=>{const pts=geoWorld(f.pts,lod,false),st=roadStyle(f.tags,lod),step=lod===0?12:lod===1?35:70;let count=0;for(let i=1;i<pts.length;i++){const A=pts[i-1],B=pts[i],len=Math.hypot(B.x-A.x,B.z-A.z),n=Math.max(1,Math.ceil(len/step));for(let k=0;k<n;k++){const t0=k/n,t1=(k+1)/n,x0=A.x+(B.x-A.x)*t0,z0=A.z+(B.z-A.z)*t0,x1=A.x+(B.x-A.x)*t1,z1=A.z+(B.z-A.z)*t1,mx=(x0+x1)/2,mz=(z0+z1)/2;if(!G.inBounds(mx,mz,bounds,4))continue;const a={x:x0,z:z0,y:G.voxelElev(x0,z0,lod)},b={x:x1,z:z1,y:G.voxelElev(x1,z1,lod)};if(st.walk&&lod===0)addSegment(group,a,b,st.width+3.2*st.walk,G.shared.sidewalk,.07,.18);const seg=addSegment(group,a,b,st.width,G.roadMat(st.color),.14,.18);if(!seg)continue;count++;if(st.mark&&lod===0&&Number(G.$('#detail').value)>0&&seg.len>10){const dash=5,gap=6,num=Math.floor(seg.len/(dash+gap));for(let j=0;j<num;j++){const off=(j+.5)*(dash+gap)-seg.len/2,cx=seg.x+seg.dx*off,cz=seg.z+seg.dz*off,p1={x:cx-seg.dx*dash/2,z:cz-seg.dz*dash/2,y:G.voxelElev(cx-seg.dx*dash/2,cz-seg.dz*dash/2,lod)},p2={x:cx+seg.dx*dash/2,z:cz+seg.dz*dash/2,y:G.voxelElev(cx+seg.dx*dash/2,cz+seg.dz*dash/2,lod)};addSegment(group,p1,p2,.2,G.shared.marking,.25,.05)}}if(lod===0&&st.walk&&len>25&&Number(G.$('#detail').value)>0){const spacing=36,nl=Math.floor(len/spacing);for(let q=0;q<nl;q++){const u=(q+.5)/nl,px=A.x+(B.x-A.x)*u,pz=A.z+(B.z-A.z)*u;lamps.push({x:px,z:pz,y:G.voxelElev(px,pz,0)})}}}}return count};
const scatterTrees=(out,pts,b,id,density)=>{if(!density||Number(G.$('#detail').value)===0)return;const q=G.boundsOf(pts),minX=Math.max(q.minX,b.minX),maxX=Math.min(q.maxX,b.maxX),minZ=Math.max(q.minZ,b.minZ),maxZ=Math.min(q.maxZ,b.maxZ),area=Math.max(0,(maxX-minX)*(maxZ-minZ)),limit=Math.min(Number(G.$('#detail').value)===2?65:30,Math.floor(area/170*density)),r=G.rng(id);for(let i=0;i<limit*6&&out.length<limit;i++){const x=minX+r()*(maxX-minX),z=minZ+r()*(maxZ-minZ);if(G.pointInPoly(x,z,pts))out.push({x,z,y:G.voxelElev(x,z,0),s:.7+r()*.9})}};
const addTrees=(g,trees)=>{if(!trees.length)return;const trunk=new THREE.InstancedMesh(new THREE.BoxGeometry(.55,3.2,.55),G.shared.trunk,trees.length),leaf=new THREE.InstancedMesh(new THREE.BoxGeometry(2.8,2.8,2.8),G.shared.leaf,trees.length),m=new THREE.Matrix4();trees.forEach((t,i)=>{m.compose(new THREE.Vector3(t.x,t.y+1.6*t.s,t.z),new THREE.Quaternion(),new THREE.Vector3(t.s,t.s,t.s));trunk.setMatrixAt(i,m);m.compose(new THREE.Vector3(t.x,t.y+4.2*t.s,t.z),new THREE.Quaternion(),new THREE.Vector3(t.s,t.s,t.s));leaf.setMatrixAt(i,m)});trunk.castShadow=leaf.castShadow=!G.MOBILE;g.add(trunk,leaf)};
const addLamps=(g,lamps)=>{const a=lamps.slice(0,80);if(!a.length)return;const pole=new THREE.InstancedMesh(new THREE.BoxGeometry(.18,4.2,.18),G.shared.lamp,a.length),glow=new THREE.InstancedMesh(new THREE.BoxGeometry(.45,.35,.45),G.shared.lampGlow,a.length),m=new THREE.Matrix4();a.forEach((p,i)=>{m.makeTranslation(p.x,p.y+2.1,p.z);pole.setMatrixAt(i,m);m.makeTranslation(p.x,p.y+4.25,p.z);glow.setMatrixAt(i,m)});g.add(pole,glow)};
const addFarBuildings=(g,items)=>{if(!items.length)return;const geo=new THREE.BoxGeometry(1,1,1),mat=G.buildingMat(0xb7ad99),mesh=new THREE.InstancedMesh(geo,mat,items.length),m=new THREE.Matrix4();items.forEach((b,i)=>{m.compose(new THREE.Vector3(b.x,b.y+b.h/2,b.z),new THREE.Quaternion(),new THREE.Vector3(b.w,b.h,b.d));mesh.setMatrixAt(i,m)});g.add(mesh)};
const addNearBuilding=(g,pts,t,id,lod,roofUnits)=>{const b=G.boundsOf(pts),h=buildingHeight(t,id,lod),color=buildingColor(t,id,lod),samples=[G.voxelElev(b.x,b.z,lod),G.voxelElev(b.minX,b.minZ,lod),G.voxelElev(b.maxX,b.minZ,lod),G.voxelElev(b.minX,b.maxZ,lod),G.voxelElev(b.maxX,b.maxZ,lod)],eMin=Math.min(...samples),eMax=Math.max(...samples),skirt=1.5+eMax-eMin;if(lod===1){const mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(3,b.w),h+skirt,Math.max(3,b.d)),G.buildingMat(color));mesh.position.set(b.x,eMin-skirt+(h+skirt)/2,b.z);mesh.receiveShadow=true;g.add(mesh);return true}const shape=G.makeShape(pts);if(!shape)return false;try{const geo=new THREE.ExtrudeGeometry(shape,{depth:h+skirt,bevelEnabled:false,steps:1,curveSegments:1});geo.rotateX(-Math.PI/2);geo.translate(0,eMin-skirt,0);geo.computeVertexNormals();const roof=G.material(G.shared.building,(0x5e5b57+(G.hash(id)%0x111111))&0xffffff,{flatShading:true}),facade=G.facadeMaterial(color);facade.userData.isFacade=true;const mesh=new THREE.Mesh(geo,[roof,facade]);mesh.receiveShadow=true;mesh.castShadow=!G.MOBILE;g.add(mesh);if(Number(G.$('#detail').value)>0&&b.w>8&&b.d>8&&G.hash(id)%3===0)roofUnits.push({x:b.x+(G.hash(id+'x')%100/100-.5)*b.w*.25,z:b.z+(G.hash(id+'z')%100/100-.5)*b.d*.25,y:eMin+h+.7,w:Math.min(4,b.w*.18),d:Math.min(4,b.d*.18)});return true}catch{return false}};
const addRoofUnits=(g,units)=>{if(!units.length)return;const mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),G.shared.roof,units.length),m=new THREE.Matrix4();units.forEach((u,i)=>{m.compose(new THREE.Vector3(u.x,u.y,u.z),new THREE.Quaternion(),new THREE.Vector3(u.w,1.4,u.d));mesh.setMatrixAt(i,m)});g.add(mesh)};
G.renderChunk=(c,source,lod)=>{const group=new THREE.Group(),bounds=G.chunkBounds(c),trees=[],lamps=[],roofs=[],farBuildings=[];group.name=`chunk-${c.key}-lod-${lod}`;group.add(G.makeTerracedTerrain(c,lod));let count=0;
 for(const f of source.areas){const pts=geoWorld(f.pts,lod,true),center=G.centroid(pts);if(pts.length<4||!G.inBounds(center.x,center.z,bounds,5))continue;const st=areaStyle(f.tags);if(lod===2&&!st.water&&G.boundsOf(pts).w*G.boundsOf(pts).d<1800)continue;const m=areaMesh(pts,st,lod);if(m){group.add(m);count++}if(lod===0)scatterTrees(trees,pts,bounds,f.id,st.trees)}
 for(const f of source.roads)count+=addRoad(group,f,bounds,lod,lamps)>0?1:0;
 for(const f of source.rails){if(lod===2)continue;const pts=geoWorld(f.pts,lod,false);for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],mx=(a.x+b.x)/2,mz=(a.z+b.z)/2;if(!G.inBounds(mx,mz,bounds,4))continue;addSegment(group,{...a,y:G.voxelElev(a.x,a.z,lod)},{...b,y:G.voxelElev(b.x,b.z,lod)},2.2,G.shared.rail,.14,.18)}count++}
 for(const f of source.waterLines){const pts=geoWorld(f.pts,lod,false);for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],mx=(a.x+b.x)/2,mz=(a.z+b.z)/2;if(!G.inBounds(mx,mz,bounds,4))continue;addSegment(group,{...a,y:G.voxelElev(a.x,a.z,lod)},{...b,y:G.voxelElev(b.x,b.z,lod)},4,G.shared.water,.1,.12)}count++}
 let built=0,limit=lod===0?(Number(G.$('#detail').value)===2?340:260):lod===1?300:400;for(const f of source.buildings){if(built>=limit)break;const raw=f.pts.map(p=>G.geoToWorld(p.lat,p.lon)),cen=G.centroid(raw);if(!G.inBounds(cen.x,cen.z,bounds,3))continue;const pts=G.cleanPoints(raw,lod,true),b=G.boundsOf(pts);if(pts.length<4||b.w<1.5||b.d<1.5)continue;const h=buildingHeight(f.tags,f.id,lod),base=G.voxelElev(b.x,b.z,lod);if(lod===2)farBuildings.push({x:G.snap(b.x,2),z:G.snap(b.z,2),y:base,w:Math.max(8,G.snap(b.w,2)),d:Math.max(8,G.snap(b.d,2)),h});else addNearBuilding(group,pts,f.tags,f.id,lod,roofs);built++;count++}
 if(lod===2)addFarBuildings(group,farBuildings);if(lod===0){addTrees(group,trees);addLamps(group,lamps);addRoofUnits(group,roofs)}
 const old=c.content;c.content=group;c.group.add(group);const oldCount=c.featureCount||0;c.featureCount=count;G.state.totalFeatures+=count-oldCount;c.lod=lod;c.state='ready';G.fadeIn(group);if(old)G.fadeOut(old,()=>G.disposeObject(old));return count};
})();
