(()=>{
'use strict';
const G=window.GeoVoxel;if(!G||G.failed)return;const $=G.$;
const params=new URLSearchParams(location.search);if(params.has('lat'))$('#lat').value=params.get('lat');if(params.has('lon'))$('#lon').value=params.get('lon');if(params.has('t'))$('#time').value=params.get('t');
G.updateURL=()=>{const f=G.getFocus(),p=G.worldToGeo(f.x,f.z),q=new URLSearchParams({lat:p.lat.toFixed(5),lon:p.lon.toFixed(5),t:$('#time').value});history.replaceState(null,'',`${location.pathname}?${q}`)};
const start=()=>{const lat=parseFloat($('#lat').value),lon=parseFloat($('#lon').value);if(!Number.isFinite(lat)||!Number.isFinite(lon)){G.status.textContent='Enter valid coordinates.';return}G.setFly?.(false);G.startWorld(lat,lon);G.updateURL()};
const findPlace=async()=>{const q=$('#search').value.trim();if(!q)return;$('#find').disabled=true;G.status.textContent=`Searching for “${q}”…`;try{let rows=[];try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});if(r.ok)rows=await r.json()}catch{}if(!rows.length){const r=await fetch(`https://photon.komoot.io/api/?limit=1&q=${encodeURIComponent(q)}`);if(r.ok){const j=await r.json();rows=(j.features||[]).map(f=>({lat:f.geometry.coordinates[1],lon:f.geometry.coordinates[0],display_name:f.properties.name||q}))}}if(!rows.length)throw Error('No result');$('#lat').value=Number(rows[0].lat).toFixed(6);$('#lon').value=Number(rows[0].lon).toFixed(6);start();G.toast(rows[0].display_name||q)}catch(e){G.status.textContent='Place search failed. Try a city plus state or country.'}finally{$('#find').disabled=false}};
$('#preset').onchange=e=>{const[a,b]=e.target.value.split(',');$('#lat').value=a;$('#lon').value=b};$('#go').onclick=start;$('#find').onclick=findPlace;$('#search').addEventListener('keydown',e=>{if(e.key==='Enter')findPlace()});$('#locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('#lat').value=p.coords.latitude.toFixed(6);$('#lon').value=p.coords.longitude.toFixed(6);start()},()=>G.status.textContent='Location permission was not granted.',{enableHighAccuracy:true,timeout:12000}):G.status.textContent='Geolocation is unavailable.';$('#radius').onchange=()=>G.desiredChunks();$('#detail').onchange=()=>G.rebuild();$('#voxel').onchange=()=>G.rebuild();$('#retry').onclick=()=>G.retry();$('#reset').onclick=()=>G.resetView();$('#fly').onclick=()=>G.setFly(!G.flight.on);$('#time').oninput=e=>{G.applyTime(Number(e.target.value));G.updateURL()};$('#share').onclick=async()=>{G.updateURL();try{if(navigator.share)await navigator.share({title:'GeoVoxel',url:location.href});else await navigator.clipboard.writeText(location.href);G.toast('Link ready to share')}catch{G.toast('Share cancelled')}};
G.applyTime(Number($('#time').value));G.resetView();G.loading.hidden=true;start();
G.renderer.setAnimationLoop(time=>{G.controls.update();G.updateFlight?.(time);G.updateStream(time);G.updateFades(time);G.updateCompass();G.renderer.render(G.scene,G.camera)});
})();
